#!/usr/bin/env bash
echo "Importing classes"
source ./scripts/functions.sh
destDir="$basedir/work/Minecraft/$version/source/"
importDir="$basedir/work/Minecraft/$version/imports"
import() {
  i="$importDir/$1.java"
  echo "Importing $i"
  cp -rf "$i" "$destDir/$1.java"
}
importRaw() {
  i="$importDir/$1"
  echo "Importing $i"
  rm -rf "$destDir/$1"
  cp -rf "$i" "$destDir/$1"
}

# nms imports
# -----------
# Use this for classes that is empty, or completely broken.
# This imports the file from another decompiler.
#
# Usage
# -----
# import <path/to/file>

import net/minecraft/Util
import net/minecraft/world/level/CommonLevelAccessor
import net/minecraft/world/level/Level
import net/minecraft/world/level/GameRules
import net/minecraft/world/level/LevelReader
import net/minecraft/world/level/timers/FunctionCallback
import net/minecraft/world/level/timers/FunctionTagCallback
import net/minecraft/world/level/timers/TimerCallbacks
import net/minecraft/world/level/storage/DerivedLevelData
import net/minecraft/world/level/storage/LevelStorageSource
import net/minecraft/world/level/storage/PrimaryLevelData
import net/minecraft/world/level/storage/ServerLevelData
import net/minecraft/world/level/storage/WorldData
import net/minecraft/world/level/newbiome/layer/AddDeepOceanLayer
import net/minecraft/world/level/newbiome/layer/AddEdgeLayer
import net/minecraft/world/level/newbiome/layer/AddIslandLayer
import net/minecraft/world/level/newbiome/layer/AddMushroomIslandLayer
import net/minecraft/world/level/newbiome/layer/AddSnowLayer
import net/minecraft/world/level/newbiome/layer/BiomeEdgeLayer
import net/minecraft/world/level/newbiome/layer/BiomeInitLayer
import net/minecraft/world/level/newbiome/layer/Layers
import net/minecraft/world/level/newbiome/layer/OceanMixerLayer
import net/minecraft/world/level/newbiome/layer/RareBiomeLargeLayer
import net/minecraft/world/level/newbiome/layer/RareBiomeSpotLayer
import net/minecraft/world/level/newbiome/layer/RegionHillsLayer
import net/minecraft/world/level/newbiome/layer/RemoveTooMuchOceanLayer
import net/minecraft/world/level/newbiome/layer/RiverInitLayer
import net/minecraft/world/level/newbiome/layer/RiverLayer
import net/minecraft/world/level/newbiome/layer/RiverMixerLayer
import net/minecraft/world/level/newbiome/layer/ShoreLayer
import net/minecraft/world/level/newbiome/layer/SmoothLayer
import net/minecraft/world/level/newbiome/layer/ZoomLayer
import net/minecraft/world/level/newbiome/layer/traits/BishopTransformer
import net/minecraft/world/level/newbiome/layer/traits/C0Transformer
import net/minecraft/world/level/newbiome/layer/traits/C1Transformer
import net/minecraft/world/level/newbiome/layer/traits/CastleTransformer
import net/minecraft/world/level/levelgen/WorldGenSettings
import net/minecraft/world/level/levelgen/structure/NetherFossilFeature
import net/minecraft/world/level/levelgen/structure/OceanRuinFeature
import net/minecraft/world/level/levelgen/structure/StructureStart
import net/minecraft/world/level/levelgen/feature/BuriedTreasureFeature
import net/minecraft/world/level/levelgen/feature/ConfiguredStructureFeature
import net/minecraft/world/level/levelgen/feature/DesertPyramidFeature
import net/minecraft/world/level/levelgen/feature/EndCityFeature
import net/minecraft/world/level/levelgen/feature/IglooFeature
import net/minecraft/world/level/levelgen/feature/JigsawFeature
import net/minecraft/world/level/levelgen/feature/JunglePyramidFeature
import net/minecraft/world/level/levelgen/feature/MineshaftFeature
import net/minecraft/world/level/levelgen/feature/NetherFortressFeature
import net/minecraft/world/level/levelgen/feature/OceanMonumentFeature
import net/minecraft/world/level/levelgen/feature/RuinedPortalFeature
import net/minecraft/world/level/levelgen/feature/ShipwreckFeature
import net/minecraft/world/level/levelgen/feature/StrongholdFeature
import net/minecraft/world/level/levelgen/feature/StructureFeature
import net/minecraft/world/level/levelgen/feature/SwamplandHutFeature
import net/minecraft/world/level/levelgen/feature/WoodlandMansionFeature
import net/minecraft/world/level/levelgen/feature/structures/JigsawPlacement
import net/minecraft/world/level/dimension/LevelStem
import net/minecraft/world/level/chunk/ChunkGenerator
import net/minecraft/world/entity/raid/Raids
import net/minecraft/world/entity/npc/Villager
import net/minecraft/util/monitoring/jmx/MinecraftServerStatistics
import net/minecraft/stats/ServerStatsCounter
import net/minecraft/server/PlayerAdvancements
import net/minecraft/server/ServerFunctionManager
import net/minecraft/server/ServerInterface
import net/minecraft/server/ServerScoreboard
import net/minecraft/server/rcon/RconConsoleSource
import net/minecraft/server/players/OldUsersConverter
import net/minecraft/server/network/MemoryServerHandshakePacketListenerImpl
import net/minecraft/server/network/ServerConnectionListener
import net/minecraft/server/network/ServerGamePacketListenerImpl
import net/minecraft/server/network/ServerHandshakePacketListenerImpl
import net/minecraft/server/network/ServerLoginPacketListenerImpl
import net/minecraft/server/network/ServerStatusPacketListenerImpl
import net/minecraft/server/level/ServerLevel
import net/minecraft/server/level/ServerPlayer
import net/minecraft/server/level/WorldGenRegion
import net/minecraft/server/gui/MinecraftServerGui
import net/minecraft/server/gui/PlayerListComponent
import net/minecraft/server/gui/StatsComponent
import net/minecraft/server/dedicated/DedicatedServerSettings
import net/minecraft/server/dedicated/ServerWatchdog
import net/minecraft/server/commands/OpCommand
import net/minecraft/server/commands/WhitelistCommand
import net/minecraft/resources/RegistryWriteOps
import net/minecraft/realms/DisconnectedRealmsScreen
import net/minecraft/network/protocol/game/ClientboundRespawnPacket
import net/minecraft/network/protocol/game/ClientGamePacketListener
import net/minecraft/commands/CommandSourceStack
import net/minecraft/commands/SharedSuggestionProvider
import net/minecraft/advancements/AdvancementRewards
import net/minecraft/client/Session
import net/minecraft/client/Options
import net/minecraft/client/MouseHandler
import net/minecraft/client/KeyboardHandler
import net/minecraft/client/Game
import net/minecraft/client/DebugQueryHandler
import net/minecraft/client/tutorial/Tutorial
import net/minecraft/client/sounds/MusicManager
import net/minecraft/client/resources/ClientPackSource
import net/minecraft/client/renderer/CubeMap
import net/minecraft/client/renderer/DimensionSpecialEffects
import net/minecraft/client/renderer/GameRenderer
import net/minecraft/client/renderer/ItemInHandRenderer
import net/minecraft/client/renderer/LevelRenderer
import net/minecraft/client/renderer/LightTexture
import net/minecraft/client/renderer/PanoramaRenderer
import net/minecraft/client/renderer/ScreenEffectRenderer
import net/minecraft/client/renderer/VirtualScreen
import net/minecraft/client/renderer/entity/ItemFrameRenderer
import net/minecraft/client/renderer/debug/BeeDebugRenderer
import net/minecraft/client/renderer/debug/BrainDebugRenderer
import net/minecraft/client/renderer/debug/ChunkBorderRenderer
import net/minecraft/client/renderer/debug/ChunkDebugRenderer
import net/minecraft/client/renderer/debug/CollisionBoxRenderer
import net/minecraft/client/renderer/debug/DebugRenderer
import net/minecraft/client/renderer/debug/GoalSelectorDebugRenderer
import net/minecraft/client/renderer/debug/HeightMapRenderer
import net/minecraft/client/renderer/debug/LightDebugRenderer
import net/minecraft/client/renderer/debug/NeighborsUpdateRenderer
import net/minecraft/client/renderer/debug/RaidDebugRenderer
import net/minecraft/client/renderer/debug/SolidFaceRenderer
import net/minecraft/client/renderer/debug/StructureRenderer
import net/minecraft/client/renderer/debug/WaterDebugRenderer
import net/minecraft/client/player/LocalPlayer
import net/minecraft/client/multiplayer/ClientAdvancements
import net/minecraft/client/multiplayer/ClientHandshakePacketListenerImpl
import net/minecraft/client/multiplayer/ClientLevel
import net/minecraft/client/multiplayer/ClientSuggestionProvider
import net/minecraft/client/multiplayer/MultiPlayerGameMode
import net/minecraft/client/multiplayer/ServerList
import net/minecraft/client/gui/Gui
import net/minecraft/client/gui/font/TextFieldHelper
import net/minecraft/client/gui/components/AbstractSelectionList
import net/minecraft/client/gui/components/AbstractSliderButton
import net/minecraft/client/gui/components/AbstractWidget
import net/minecraft/client/gui/components/BossHealthOverlay
import net/minecraft/client/gui/components/ChatComponent
import net/minecraft/client/gui/components/CommandSuggestions
import net/minecraft/client/gui/components/ContainerObjectSelectionList
import net/minecraft/client/gui/components/DebugScreenOverlay
import net/minecraft/client/gui/components/ObjectSelectionList
import net/minecraft/client/gui/components/OptionsList
import net/minecraft/client/gui/components/PlayerTabOverlay
import net/minecraft/client/gui/components/SubtitleOverlay
import net/minecraft/client/gui/components/VolumeSlider
import net/minecraft/client/gui/components/toasts/SystemToast
import net/minecraft/client/gui/components/toasts/ToastComponent
import net/minecraft/client/gui/components/spectator/SpectatorGui
import net/minecraft/client/gui/chat/OverlayChatListener
import net/minecraft/client/gui/chat/StandardChatListener
import net/minecraft/client/color/item/ItemColors
import net/minecraft/client/color/block/BlockColors
import com/mojang/realmsclient/RealmsMainScreen
import com/mojang/realmsclient/util/task/LongRunningTask
import net/minecraft/CrashReport
import net/minecraft/ChatFormatting
import net/minecraft/world/entity/Entity
import net/minecraft/world/SimpleContainer
import net/minecraft/world/scores/Team
import net/minecraft/world/level/biome/Biome
import net/minecraft/world/level/biome/BiomeGenerationSettings
import net/minecraft/world/level/biome/BiomeSource
import net/minecraft/world/level/biome/BiomeSpecialEffects
import net/minecraft/world/level/biome/MobSpawnSettings
import net/minecraft/world/level/block/entity/BeaconBlockEntity
import net/minecraft/world/level/block/entity/CommandBlockEntity
import net/minecraft/world/level/block/entity/HopperBlockEntity
import net/minecraft/world/level/block/entity/JigsawBlockEntity
import net/minecraft/world/level/block/entity/LecternBlockEntity
import net/minecraft/world/level/block/entity/RandomizableContainerBlockEntity
import net/minecraft/world/level/block/entity/SignBlockEntity
import net/minecraft/world/level/block/entity/StructureBlockEntity
import net/minecraft/world/level/block/state/properties/DirectionProperty
import net/minecraft/world/level/block/state/properties/EnumProperty
import net/minecraft/world/level/block/state/BlockBehaviour
import net/minecraft/world/level/block/state/StateHolder
import net/minecraft/world/level/block/state/StateDefinition
import net/minecraft/world/level/block/BedBlock
import net/minecraft/world/level/block/CrossCollisionBlock
import net/minecraft/world/level/block/DaylightDetectorBlock
import net/minecraft/world/level/block/EndPortalBlock
import net/minecraft/world/level/block/FireBlock
import net/minecraft/world/level/block/IceBlock
import net/minecraft/world/level/block/NetherPortalBlock
import net/minecraft/world/level/block/RespawnAnchorBlock
import net/minecraft/world/level/block/VineBlock
import net/minecraft/world/level/block/WetSpongeBlock
import net/minecraft/world/level/chunk/storage/ChunkSerializer
import net/minecraft/world/level/chunk/storage/SectionStorage
import net/minecraft/world/level/chunk/ChunkStatus
import net/minecraft/world/level/chunk/EmptyLevelChunk
import net/minecraft/world/level/chunk/LevelChunk
import net/minecraft/world/level/chunk/PalettedContainer
import net/minecraft/world/level/levelgen/feature/configurations/RandomPatchConfiguration
import net/minecraft/world/level/levelgen/feature/structures/ListPoolElement
import net/minecraft/world/level/levelgen/feature/structures/StructurePoolElement
import net/minecraft/world/level/levelgen/feature/structures/StructureTemplatePool
import net/minecraft/world/level/levelgen/feature/treedecorators/BeehiveDecorator
import net/minecraft/world/level/levelgen/feature/BonusChestFeature
import net/minecraft/world/level/levelgen/feature/FossilFeature
import net/minecraft/world/level/levelgen/feature/SpikeFeature
import net/minecraft/world/level/levelgen/structure/templatesystem/StructureTemplate
import net/minecraft/world/level/levelgen/structure/RuinedPortalPiece
import net/minecraft/world/level/levelgen/synth/PerlinNoise
import net/minecraft/world/level/levelgen/synth/PerlinSimplexNoise
import net/minecraft/world/level/levelgen/DebugLevelSource
import net/minecraft/world/level/levelgen/GenerationStep
import net/minecraft/world/level/levelgen/PhantomSpawner
import net/minecraft/world/level/material/LavaFluid
import net/minecraft/world/level/pathfinder/PathFinder
import net/minecraft/world/level/saveddata/maps/MapItemSavedData
import net/minecraft/world/level/storage/loot/entries/LootPoolSingletonContainer
import net/minecraft/world/level/storage/loot/functions/ApplyBonusCount
import net/minecraft/world/level/storage/loot/functions/ApplyExplosionDecay
import net/minecraft/world/level/storage/loot/functions/CopyblockState
import net/minecraft/world/level/storage/loot/functions/CopyNameFunction
import net/minecraft/world/level/storage/loot/functions/EnchantRandomlyFunction
import net/minecraft/world/level/storage/loot/functions/SetLoreFunction
import net/minecraft/world/level/storage/loot/functions/SmeltItemFunction
import net/minecraft/world/level/storage/loot/Deserializers
import net/minecraft/world/level/storage/loot/LootContext
import net/minecraft/world/level/storage/loot/LootPool
import net/minecraft/world/level/storage/loot/LootTable
import net/minecraft/world/level/BaseCommandBlock
import net/minecraft/world/level/ChunkPos
import net/minecraft/world/level/ChunkTickList
import net/minecraft/world/level/CollisionGetter
import net/minecraft/world/level/LevelAccessor
import net/minecraft/world/level/LevelTimeAccess
import net/minecraft/world/level/NaturalSpawner
import net/minecraft/world/item/crafting/Ingredient
import net/minecraft/world/item/crafting/RecipeManager
import net/minecraft/world/item/BlockItem
import net/minecraft/world/item/BucketItem
import net/minecraft/world/item/DyeColor
import net/minecraft/world/item/ItemStack
import net/minecraft/world/item/KnowledgeBookItem
import net/minecraft/world/item/MapItem
import net/minecraft/world/inventory/CraftingMenu
import net/minecraft/world/inventory/EnchantmentMenu
import net/minecraft/world/inventory/GrindstoneMenu
import net/minecraft/world/entity/TamableAnimal
import net/minecraft/world/entity/MobCategory
import net/minecraft/world/entity/LivingEntity
import net/minecraft/world/entity/EntityType
import net/minecraft/world/entity/vehicle/AbstractMinecartContainer
import net/minecraft/world/entity/vehicle/MinecartCommandBlock
import net/minecraft/world/entity/schedule/Schedule
import net/minecraft/world/entity/schedule/ScheduleBuilder
import net/minecraft/world/entity/projectile/FishingHook
import net/minecraft/world/entity/npc/VillagerTrades
import net/minecraft/world/entity/monster/hoglin/Hoglin
import net/minecraft/world/entity/monster/piglin/AbstractPiglin
import net/minecraft/world/entity/monster/piglin/PiglinAi
import net/minecraft/world/entity/animal/horse/AbstractHorse
import net/minecraft/world/entity/animal/Bee
import net/minecraft/world/entity/animal/Cat
import net/minecraft/world/entity/animal/Fox
import net/minecraft/world/entity/animal/IronGolem
import net/minecraft/world/entity/animal/Sheep
import net/minecraft/world/entity/ai/attributes/AttributeMap
import net/minecraft/world/entity/ai/behavior/AcquirePoi
import net/minecraft/world/entity/ai/behavior/AssignProfessionFromJobSite
import net/minecraft/world/entity/ai/behavior/GateBehavior
import net/minecraft/world/entity/ai/behavior/GiveGiftToHero
import net/minecraft/world/entity/ai/behavior/GoToPotentialJobSite
import net/minecraft/world/entity/ai/behavior/InsideBrownianWalk
import net/minecraft/world/entity/ai/behavior/TradeWithVillager
import net/minecraft/world/entity/ai/behavior/ValidateNearbyPoi
import net/minecraft/world/entity/ai/goal/GolemRandomStrollInVillageGoal
import net/minecraft/world/entity/ai/gossip/GossipContainer
import net/minecraft/world/entity/ai/gossip/GossipType
import net/minecraft/world/entity/ai/navigation/PathNavigation
import net/minecraft/world/entity/ai/sensing/NearestLivingEntitySensor
import net/minecraft/world/entity/ai/sensing/PlayerSensor
import net/minecraft/world/entity/ai/sensing/VillagerBabiesSensor
import net/minecraft/world/entity/ai/village/poi/PoiManager
import net/minecraft/world/entity/ai/village/poi/PoiType
import net/minecraft/util/datafix/fixes/AddNewChoices
import net/minecraft/util/datafix/fixes/ChunkToProtochunkFix
import net/minecraft/util/datafix/fixes/ItemStackTheFlatteningFix
import net/minecraft/util/datafix/fixes/LeavesFix
import net/minecraft/util/datafix/fixes/LevelDataGeneratorOptionsFix
import net/minecraft/util/datafix/fixes/LevelFlatGeneratorInfoFix
import net/minecraft/util/datafix/fixes/NewVillageFix
import net/minecraft/util/datafix/fixes/OptionsKeyLwjgl3Fix
import net/minecraft/util/datafix/fixes/OptionsKeyTranslationFix
import net/minecraft/util/datafix/fixes/SimplestEntityRenameFix
import net/minecraft/util/datafix/fixes/WorldGenSettingsFix
import net/minecraft/util/datafix/DataFixers
import net/minecraft/util/thread/StrictQueue
import net/minecraft/util/ClassInstanceMultiMap
import net/minecraft/util/CsvOutput
import net/minecraft/util/RewindableStream
import net/minecraft/tags/SerializationTags
import net/minecraft/tags/StaticTagHelper
import net/minecraft/tags/TagLoader
import net/minecraft/tags/TagManager
import net/minecraft/sounds/SoundSource
import com/mojang/blaze3d/systems/RenderSystem
import com/mojang/blaze3d/vertex/VertexFormat
import com/mojang/math/OctahedralGroup
import com/mojang/realmsclient/client/FileDownload
import com/mojang/realmsclient/client/RealmsClient
import com/mojang/realmsclient/dto/RealmsServer
import com/mojang/realmsclient/gui/RealmsDataFetcher
import com/mojang/realmsclient/gui/RealmsWorldSlotButton
import com/mojang/realmsclient/util/RealmsPersistence
import com/mojang/realmsclient/util/RealmsTextureManager
import com/mojang/realmsclient/util/RealmsUtil
import com/mojang/realmsclient/util/task/ConnectTask
import com/mojang/realmsclient/util/task/GetServerDetailsTask
import net/minecraft/advancements/critereon/ChanneledLightningTrigger
import net/minecraft/advancements/critereon/LocationPredicate
import net/minecraft/advancements/critereon/PlayerPredicate
import net/minecraft/client/ClientRecipeBook
import net/minecraft/client/KeyMapping
import net/minecraft/client/Option
import net/minecraft/client/StringSplitter
import net/minecraft/client/User
import net/minecraft/client/gui/MapRenderer
import net/minecraft/client/gui/chat/NarratorChatListener
import net/minecraft/client/gui/components/AbstractButton
import net/minecraft/client/gui/components/Checkbox
import net/minecraft/client/gui/components/ComponentRenderUtils
import net/minecraft/client/gui/components/EditBox
import net/minecraft/client/gui/components/ImageButton
import net/minecraft/client/gui/components/LockIconButton
import net/minecraft/client/gui/components/MultiLineLabel
import net/minecraft/client/gui/components/StateSwitchingButton
import net/minecraft/client/gui/components/toasts/AdvancementToast
import net/minecraft/client/gui/components/toasts/RecipeToast
import net/minecraft/client/gui/components/toasts/TutorialToast
import net/minecraft/client/gui/font/providers/LegacyUnicodeBitmapsProvider
import net/minecraft/client/gui/spectator/PlayerMenuItem
import net/minecraft/client/gui/spectator/SpectatorMenu
import net/minecraft/client/gui/spectator/categories/TeleportToPlayerMenuCategory
import net/minecraft/client/gui/spectator/categories/TeleportToTeamMenuCategory
import net/minecraft/client/main/Main
import net/minecraft/client/model/GuardianModel
import net/minecraft/client/multiplayer/ClientChunkCache
import net/minecraft/client/multiplayer/PlayerInfo
import net/minecraft/client/particle/BarrierParticle
import net/minecraft/client/particle/BreakingItemParticle
import net/minecraft/client/particle/FallingDustParticle
import net/minecraft/client/particle/FireworkParticles
import net/minecraft/client/particle/MobAppearanceParticle
import net/minecraft/client/particle/ParticleDescription
import net/minecraft/client/particle/ParticleEngine
import net/minecraft/client/particle/TerrainParticle
import net/minecraft/client/player/AbstractClientPlayer
import net/minecraft/client/player/RemotePlayer
import net/minecraft/client/renderer/ChunkBufferBuilderPack
import net/minecraft/client/renderer/ItemBlockRenderTypes
import net/minecraft/client/renderer/PostChain
import net/minecraft/client/renderer/PostPass
import net/minecraft/client/renderer/RenderStateShard
import net/minecraft/client/renderer/Sheets
import net/minecraft/client/renderer/block/LiquidBlockRenderer
import net/minecraft/client/renderer/block/ModelBlockRenderer
import net/minecraft/client/renderer/block/model/BlockModel
import net/minecraft/client/renderer/block/model/ItemOverrides
import net/minecraft/client/renderer/block/model/MultiVariant
import net/minecraft/client/renderer/block/model/multipart/AndCondition
import net/minecraft/client/renderer/block/model/multipart/KeyValueCondition
import net/minecraft/client/renderer/block/model/multipart/MultiPart
import net/minecraft/client/renderer/block/model/multipart/OrCondition
import net/minecraft/client/renderer/block/model/multipart/Selector
import net/minecraft/client/renderer/blockentity/CampfireRenderer
import net/minecraft/client/renderer/blockentity/PistonHeadRenderer
import net/minecraft/client/renderer/blockentity/SkullBlockRenderer
import net/minecraft/client/renderer/blockentity/SpawnerRenderer
import net/minecraft/client/renderer/blockentity/StructureBlockRenderer
import net/minecraft/client/renderer/blockentity/TheEndPortalRenderer
import net/minecraft/client/renderer/chunk/ChunkRenderDispatcher
import net/minecraft/client/renderer/entity/EntityRenderDispatcher
import net/minecraft/client/renderer/entity/EntityRenderer
import net/minecraft/client/renderer/entity/FallingBlockRenderer
import net/minecraft/client/renderer/entity/FishingHookRenderer
import net/minecraft/client/renderer/entity/ItemRenderer
import net/minecraft/client/renderer/entity/LivingEntityRenderer
import net/minecraft/client/renderer/entity/MinecartRenderer
import net/minecraft/client/renderer/entity/PaintingRenderer
import net/minecraft/client/renderer/entity/TntMinecartRenderer
import net/minecraft/client/renderer/entity/layers/CarriedBlockLayer
import net/minecraft/client/renderer/entity/layers/CrossedArmsItemLayer
import net/minecraft/client/renderer/entity/layers/CustomHeadLayer
import net/minecraft/client/renderer/entity/layers/DolphinCarryingItemLayer
import net/minecraft/client/renderer/entity/layers/FoxHeldItemLayer
import net/minecraft/client/renderer/entity/layers/IronGolemFlowerLayer
import net/minecraft/client/renderer/entity/layers/ItemInHandLayer
import net/minecraft/client/renderer/entity/layers/MushroomCowMushroomLayer
import net/minecraft/client/renderer/entity/layers/PandaHoldsItemLayer
import net/minecraft/client/renderer/entity/layers/SnowGolemHeadLayer
import net/minecraft/client/renderer/item/ItemProperties
import net/minecraft/client/renderer/texture/AtlasSet
import net/minecraft/client/renderer/texture/HttpTexture
import net/minecraft/client/renderer/texture/MissingTextureAtlasSprite
import net/minecraft/client/renderer/texture/Stitcher
import net/minecraft/client/renderer/texture/TextureAtlas
import net/minecraft/client/renderer/texture/TextureManager
import net/minecraft/client/resources/AssetIndex
import net/minecraft/client/resources/DirectAssetIndex
import net/minecraft/client/resources/PackResourcesAdapterV4
import net/minecraft/client/resources/SkinManager
import net/minecraft/client/resources/SplashManager
import net/minecraft/client/resources/metadata/animation/VillagerMetaDataSection
import net/minecraft/client/resources/model/BlockModelRotation
import net/minecraft/client/resources/model/Material
import net/minecraft/client/resources/model/ModelBakery
import net/minecraft/client/resources/sounds/BeeSoundInstance
import net/minecraft/client/tutorial/CraftPlanksTutorialStep
import net/minecraft/client/tutorial/FindTreeTutorialStepInstance
import net/minecraft/client/tutorial/MovementTutorialStepInstance
import net/minecraft/client/tutorial/OpenInventoryTutorialStep
import net/minecraft/client/tutorial/PunchTreeTutorialStepInstance
import net/minecraft/commands/Commands
import net/minecraft/commands/arguments/DimensionArgument
import net/minecraft/commands/arguments/GameProfileArgument
import net/minecraft/commands/arguments/ObjectiveArgument
import net/minecraft/commands/arguments/ResourceLocationArgument
import net/minecraft/commands/arguments/ScoreHolderArgument
import net/minecraft/commands/arguments/TeamArgument
import net/minecraft/commands/arguments/blocks/BlockPredicateArgument
import net/minecraft/commands/arguments/item/FunctionArgument
import net/minecraft/commands/arguments/item/ItemPredicateArgument
import net/minecraft/commands/arguments/selector/EntitySelector
import net/minecraft/commands/arguments/selector/options/EntitySelectorOptions
import net/minecraft/commands/synchronization/SuggestionProviders
import net/minecraft/core/BlockPos
import net/minecraft/core/Direction
import net/minecraft/core/SectionPos
import net/minecraft/data/HashCache
import net/minecraft/data/Main
import net/minecraft/data/advancements/AdvancementProvider
import net/minecraft/data/loot/ChestLoot
import net/minecraft/data/loot/EntityLoot
import net/minecraft/data/loot/FishingLoot
import net/minecraft/data/loot/GiftLoot
import net/minecraft/data/loot/LootTableProvider
import net/minecraft/data/loot/PiglinBarterLoot
import net/minecraft/data/models/BlockModelGenerators
import net/minecraft/data/models/ModelProvider
import net/minecraft/data/models/blockstates/Condition
import net/minecraft/data/models/blockstates/MultiVariantGenerator
import net/minecraft/data/models/blockstates/PropertyDispatch
import net/minecraft/data/models/blockstates/Selector
import net/minecraft/data/models/model/ModelTemplate
import net/minecraft/data/recipes/RecipeProvider
import net/minecraft/data/tags/TagsProvider
import net/minecraft/gametest/framework/GameTestRegistry
import net/minecraft/gametest/framework/GameTestRunner
import net/minecraft/gametest/framework/StructureUtils
import net/minecraft/gametest/framework/TestCommand
import net/minecraft/locale/Language
import net/minecraft/network/ConnectionProtocol
import net/minecraft/network/chat/ClickEvent
import net/minecraft/network/chat/HoverEvent
import net/minecraft/network/chat/NbtComponent
import net/minecraft/network/chat/ScoreComponent
import net/minecraft/network/chat/TextColor
import net/minecraft/network/protocol/PacketUtils
import net/minecraft/realms/RealmsBridge
import net/minecraft/realms/RealmsConnect
import net/minecraft/realms/RealmsLabel
import net/minecraft/realms/RealmsObjectSelectionList
import net/minecraft/realms/RealmsScreen
import net/minecraft/resources/RegistryDataPackCodec
import net/minecraft/resources/RegistryFileCodec
import net/minecraft/resources/RegistryLookupCodec
import net/minecraft/server/ServerFunctionLibrary
import net/minecraft/server/commands/AdvancementCommands
import net/minecraft/server/commands/BanIpCommands
import net/minecraft/server/commands/BanListCommands
import net/minecraft/server/commands/BanPlayerCommands
import net/minecraft/server/commands/BossBarCommands
import net/minecraft/server/commands/DataPackCommand
import net/minecraft/server/commands/DebugCommand
import net/minecraft/server/commands/DefaultGameModeCommands
import net/minecraft/server/commands/DeOpCommands
import net/minecraft/server/commands/DifficultyCommand
import net/minecraft/server/commands/EmoteCommands
import net/minecraft/server/commands/ExecuteCommand
import net/minecraft/server/commands/FunctionCommand
import net/minecraft/server/commands/GameRuleCommand
import net/minecraft/server/commands/ListPlayersCommand
import net/minecraft/server/commands/LocateBiomeCommand
import net/minecraft/server/commands/LootCommand
import net/minecraft/server/commands/PardonCommand
import net/minecraft/server/commands/PardonIpCommand
import net/minecraft/server/commands/ParticleCommand
import net/minecraft/server/commands/PublishCommand
import net/minecraft/server/commands/RecipeCommand
import net/minecraft/server/commands/ReloadCommand
import net/minecraft/server/commands/SaveAllCommand
import net/minecraft/server/commands/SaveOffCommand
import net/minecraft/server/commands/SaveOnCommand
import net/minecraft/server/commands/SayCommand
import net/minecraft/server/commands/ScheduleCommand
import net/minecraft/server/commands/ScoreboardCommand
import net/minecraft/server/commands/SetPlayerIdleTimeoutCommand
import net/minecraft/server/commands/StopCommand
import net/minecraft/server/commands/TeamCommand
import net/minecraft/server/commands/TeamMsgCommand
import net/minecraft/server/commands/TimeCommand
import net/minecraft/server/commands/TriggerCommand
import net/minecraft/server/commands/data/DataCommands
import net/minecraft/server/commands/data/StorageDataAccessor
import net/minecraft/server/level/ChunkMap
import net/minecraft/server/level/ChunkTaskPriorityQueue
import net/minecraft/server/level/ChunkTaskPriorityQueueSorter
import net/minecraft/server/level/PlayerRespawnLogic
import net/minecraft/server/level/ServerPlayerGameMode
import net/minecraft/server/network/LegacyQueryHandler
import net/minecraft/server/packs/repository/PackRepository
import net/minecraft/server/packs/resources/SimpleReloadableResourceManager
import net/minecraft/server/rcon/thread/QueryThreadGs4
import net/minecraft/server/rcon/thread/RconThread
import net/minecraft/stats/StatFormatter
import net/minecraft/core/Registry
import net/minecraft/server/MinecraftServer
import net/minecraft/server/Main
import net/minecraft/world/level/dimension/DimensionType
import net/minecraft/client/Minecraft
import net/minecraft/client/multiplayer/ClientPacketListener
import net/minecraft/world/entity/animal/Cat
import net/minecraft/core/RegistryAccess
import net/minecraft/client/server/IntegratedServer
import net/minecraft/resources/RegistryReadOps
import net/minecraft/server/players/PlayerList
import net/minecraft/world/level/storage/McRegionUpgrader
import net/minecraft/client/gui/screens/Screen
import net/minecraft/client/gui/screens/ChatScreen
import net/minecraft/client/gui/screens/ConnectScreen
import net/minecraft/client/gui/screens/CreateBuffetWorldScreen
import net/minecraft/client/gui/screens/CreateFlatWorldScreen
import net/minecraft/client/gui/screens/DirectJoinServerScreen
import net/minecraft/client/gui/screens/EditServerScreen
import net/minecraft/client/gui/screens/LanguageSelectScreen
import net/minecraft/client/gui/screens/LoadingOverlay
import net/minecraft/client/gui/screens/MenuScreens
import net/minecraft/client/gui/screens/PopupScreen
import net/minecraft/client/gui/screens/BackupConfirmScreen
import net/minecraft/client/gui/screens/ConfirmLinkScreen
import net/minecraft/client/gui/screens/DatapackLoadFailureScreen
import net/minecraft/client/gui/screens/DeathScreen
import net/minecraft/client/gui/screens/DemoIntroScreen
import net/minecraft/client/gui/screens/DisconnectedScreen
import net/minecraft/client/gui/screens/ErrorScreen
import net/minecraft/client/gui/screens/InBedChatScreen
import net/minecraft/client/gui/screens/MouseSettingsScreen
import net/minecraft/client/gui/screens/OptionsScreen
import net/minecraft/client/gui/screens/OptionsSubScreen
import net/minecraft/client/gui/screens/OutOfMemoryScreen
import net/minecraft/client/gui/screens/PauseScreen
import net/minecraft/client/gui/screens/ProgressScreen
import net/minecraft/client/gui/screens/ShareToLanScreen
import net/minecraft/client/gui/screens/SimpleOptionsSubScreen
import net/minecraft/client/gui/screens/SkinCustomizationScreen
import net/minecraft/client/gui/screens/SoundOptionsScreen
import net/minecraft/client/gui/screens/VideoSettingsScreen
import net/minecraft/client/gui/screens/WinScreen
import net/minecraft/client/gui/screens/TitleScreen
import net/minecraft/client/gui/screens/recipebook/GhostRecipe
import net/minecraft/client/gui/screens/recipebook/OverlayRecipeComponent
import net/minecraft/client/gui/screens/recipebook/RecipeBookComponent
import net/minecraft/client/gui/screens/recipebook/RecipeBookPage
import net/minecraft/client/gui/screens/recipebook/RecipeBookTabButton
import net/minecraft/client/gui/screens/recipebook/AbstractFurnaceRecipeBookComponent
import net/minecraft/client/gui/screens/recipebook/RecipeButton
import net/minecraft/client/gui/screens/packs/PackSelectionScreen
import net/minecraft/client/gui/screens/packs/TransferableSelectionList
import net/minecraft/client/gui/screens/packs/PackSelectionModel
import net/minecraft/client/gui/screens/multiplayer/ServerSelectionList
import net/minecraft/client/gui/screens/multiplayer/JoinMultiplayerScreen
import net/minecraft/client/gui/screens/multiplayer/SafetyScreen
import net/minecraft/client/gui/screens/inventory/AbstractContainerScreen
import net/minecraft/client/gui/screens/inventory/AbstractCommandBlockEditScreen
import net/minecraft/client/gui/screens/inventory/AbstractFurnaceScreen
import net/minecraft/client/gui/screens/inventory/BookEditScreen
import net/minecraft/client/gui/screens/inventory/BookViewScreen
import net/minecraft/client/gui/screens/inventory/BrewingStandScreen
import net/minecraft/client/gui/screens/inventory/CartographyTableScreen
import net/minecraft/client/gui/screens/inventory/ContainerScreen
import net/minecraft/client/gui/screens/inventory/CraftingScreen
import net/minecraft/client/gui/screens/inventory/DispenserScreen
import net/minecraft/client/gui/screens/inventory/EffectRenderingInventoryScreen
import net/minecraft/client/gui/screens/inventory/EnchantmentScreen
import net/minecraft/client/gui/screens/inventory/GrindstoneScreen
import net/minecraft/client/gui/screens/inventory/HopperScreen
import net/minecraft/client/gui/screens/inventory/HorseInventoryScreen
import net/minecraft/client/gui/screens/inventory/InventoryScreen
import net/minecraft/client/gui/screens/inventory/ItemCombinerScreen
import net/minecraft/client/gui/screens/inventory/LecternScreen
import net/minecraft/client/gui/screens/inventory/LoomScreen
import net/minecraft/client/gui/screens/inventory/MerchantScreen
import net/minecraft/client/gui/screens/inventory/MinecartCommandBlockEditScreen
import net/minecraft/client/gui/screens/inventory/PageButton
import net/minecraft/client/gui/screens/inventory/ShulkerBoxScreen
import net/minecraft/client/gui/screens/inventory/SignEditScreen
import net/minecraft/client/gui/screens/inventory/StoneCutterScreen
import net/minecraft/client/gui/screens/inventory/AnvilScreen
import net/minecraft/client/gui/screens/inventory/BeaconScreen
import net/minecraft/client/gui/screens/inventory/CommandBlockEditScreen
import net/minecraft/client/gui/screens/inventory/CreativeInventoryListener
import net/minecraft/client/gui/screens/inventory/CreativeModeInventoryScreen
import net/minecraft/client/gui/screens/inventory/JigsawBlockEditScreen
import net/minecraft/client/gui/screens/inventory/StructureBlockEditScreen
import net/minecraft/client/gui/screens/debug/GameModeSwitcherScreen
import net/minecraft/client/gui/screens/controls/ControlList
import net/minecraft/client/gui/screens/controls/ControlsScreen
import net/minecraft/client/gui/screens/advancements/AdvancementTab
import net/minecraft/client/gui/screens/advancements/AdvancementWidget
import net/minecraft/client/gui/screens/advancements/AdvancementsScreen
import net/minecraft/client/gui/screens/achievement/StatsScreen
import net/minecraft/client/gui/screens/PresetFlatWorldScreen
import net/minecraft/client/server/IntegratedPlayerList
import net/minecraft/network/protocol/game/ClientboundLoginPacket
import net/minecraft/world/level/newbiome/layer/traits/AreaTransformer1
import net/minecraft/world/level/newbiome/layer/traits/AreaTransformer2
import net/minecraft/server/dedicated/DedicatedServerProperties
import net/minecraft/server/dedicated/Settings
import net/minecraft/server/dedicated/DedicatedServer
import net/minecraft/server/dedicated/DedicatedPlayerList
import net/minecraft/util/datafix/fixes/EntityEquipmentToArmorAndHandFix
import net/minecraft/util/datafix/fixes/EntityRidingToPassengersFix
import net/minecraft/data/loot/BlockLoot
import net/minecraft/world/level/chunk/storage/OldChunkStorage
import net/minecraft/client/sounds/SoundEngine # procyon version seems broken, so we import the cfr version.

importRaw com/mojang/realmsclient/gui/screens
importRaw net/minecraft/client/gui/screens/worldselection
