name: Build (JDK 17)

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: saulmaldonado/skip-workflow@v1.1.0
      id: skip-workflow
      with:
        phrase: /\[ci-skip\]/i
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v2
      if: ${{ !steps.skip-workflow.outputs.skip }}
    - name: Pre-build step
      if: ${{ !steps.skip-workflow.outputs.skip }}
      run: 'git submodule init && git submodule update && git config --global user.email me@acrylicstyle.xyz && git config --global user.name acrylic-style'
    - name: Set up JDK 17
      if: ${{ !steps.skip-workflow.outputs.skip }}
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Apply patches
      if: ${{ !steps.skip-workflow.outputs.skip }}
      run: ./magma p
    - name: Build with Maven
      if: ${{ !steps.skip-workflow.outputs.skip }}
      run: mvn -B package --file pom.xml
    - name: Cache files
      if: ${{ !steps.skip-workflow.outputs.skip }}
      uses: actions/cache@v2.1.5
      with:
        path: '$HOME/.m2/repository'
        key: 'maven-dependencies'
